[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
tokio-rustls = "0.23.1"
rustls-native-certs = "0.6"

protocol = { path = "../protocol" }
futures = { version = "0.3" }
thiserror = "1"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry"] }
iced = { version = "0.3" }
wrapper = { path = "../wrapper" }

[dev-dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry"] }
server = { path = "../server" }

[features]
deployed = []
