[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros", "net", "sync", "rt-multi-thread"] }
protocol = { path = "../protocol" }
futures = { version = "0.3" }

rust-argon2 = "0.8"
rand = "0.8"
uuid = { version = "0.8", features = ["serde", "v4"] }
typed-sled = "0.1.14"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"

dialoguer = "0.9.0"
thiserror = "1.0"

tracing = "0.1"
tracing-subscriber = "0.3"
sync = { path = "../sync" }

[features]
testing = []
