[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
protocol = { path = "../protocol" }
futures = { version = "0.3" }

rust-argon2 = "0.8"
rand = "0.8"
uuid = { version = "0.8", features = ["serde", "v4"] }
typed-sled = { version = "0.1", git = "https://github.com/dvdsk/typed-sled", branch = "patch-3" }
serde = { version = "1", features = ["derive"] }
structopt = "0.3"

dialoguer = "0.9.0"
thiserror = "1.0"

[features]
testing = []
